export const css = {
  colorPrimary: "#5580FE",
  colorPrimaryGradient: "linear-gradient(to bottom, #8EB7FF, #4170F2)",
  colorSuccess: "#17C295",
  colorWarning: "#FE724D",
  colorDanger: "#FE6B67",
  colorLight: "#576A95",
  colorGrey: "#F6F7F9",
  colorWhite: "#FFFFFF",
  colorTitleFirst: "#16171B",
  colorTitleSecond: "#9B9DAF",
  colorTitleThird: "#CACBD4",
  colorDevide: "#E8E8E8",
  colorBackground: "#F5F6F9",

  fontSizeSmall: "12px",
  fontSize: "14px",
  fontSizeBig: "16px",
  fontSizeTitle: "18px",
  fontSizeLarge: "32px",
};
